CREATE DATABASE QLDIEM
USE DATABASE QLDIEM
CREATE DATABASE DMKHOA
( MAKHOA Char(2) NOT NULL,
  TENKHOA nvarchar(30) NOT NULL,
  CONSTRAINT PK_DMKHOA PRIMARY KEY (DMKHOA),
)
CREATE DATABASE DMSV
( MASV Char(3) NOT NULL,
  HOSV nvarchar(30) NOT NULL,
  TENSV nvarchar(20) NOT NULL,
  PHAI Int NOT NULL,
  NGAYSINH Datetime NOT NULL,
  NOISINH nvarchar(25) NOT NULL,
  MAKH Char(2) NOT NULL,
  HOCBONG float NOT NULL,
  CONSTRAINT PK_SV PRIMARY KEY (DMSV),
  CONSTRAINT FK_MAKH FOREIGN KEY REFERENCES(MAKH),
)